import pickle
import pandas as pd
import talib
import numpy as np

'''
with open("sp&500_tick.pickle", "rb") as f:
    ticker_list = pickle.load(f)

for ticker_item in ticker_list:
    df = pd.read_csv("SP_500_data/{}.csv".format(ticker_item))
    if 'Adj Close' in df.columns:
        Close = 'Adj Close'
    elif 'Adj. Close' in df.columns:
        Close = 'Adj. Close'
    #print(df[Close])
    df['SMA_200'] = talib.SMA(np.asarray(df[Close]), 200)
    df.to_csv("SP_500_data/{}.csv".format(ticker_item))
'''
df = pd.read_csv("SP_500_data/AAPL.csv")
close = np.asarray(df['Adj Close'])
#========Overlap Studies============
upperband, middleband, lowerband = talib.BBANDS(close, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
DEMA = talib.DEMA(close, timeperiod=30)
EMA = talib.EMA(close, timeperiod=30)
HT_TRENDLINE = talib.HT_TRENDLINE(close)
KAMA = talib.KAMA(close, timeperiod=30)
MA = talib.MA(close, timeperiod=30)
mama, fama = talib.MAMA(close, fastlimit=0, slowlimit=0)
#MAVP(close, periods, minperiod=2, maxperiod=30, matype=0)
MIDPOINT = talib.MIDPOINT(close, timeperiod=14)
#MIDPRICE(high, low, timeperiod=14)
#SAR(high, low, acceleration=0, maximum=0)
#SAREXT(high, low, startvalue=0, offsetonreverse=0, accelerationinitlong=0, accelerationlong=0, accelerationmaxlong=0, accelerationinitshort=0, accelerationshort=0, accelerationmaxshort=0)
SMA = talib.SMA(close, timeperiod=30)
T3 = talib.T3(close, timeperiod=5, vfactor=0)
TEMA = talib.TEMA(close, timeperiod=30)
TRIMA = talib.TRIMA(close, timeperiod=30)
WMA = talib.WMA(close, timeperiod=30)

#=====================Momentum Indicator Functions==============
#ADX(high, low, close, timeperiod=14)
#ADXR(high, low, close, timeperiod=14)
#APO(close, fastperiod=12, slowperiod=26, matype=0)
#aroondown, aroonup = AROON(high, low, timeperiod=14)
#AROONOSC(high, low, timeperiod=14)
#BOP(open, high, low, close)
#CCI(high, low, close, timeperiod=14)
#CMO(close, timeperiod=14)
#DX(high, low, close, timeperiod=14)
#macd, macdsignal, macdhist = MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)
#macd, macdsignal, macdhist = MACDEXT(close, fastperiod=12, fastmatype=0, slowperiod=26, slowmatype=0, signalperiod=9, signalmatype=0)
#macd, macdsignal, macdhist = MACDFIX(close, signalperiod=9)
#MFI(high, low, close, volume, timeperiod=14)
#MINUS_DI(high, low, close, timeperiod=14)
#MINUS_DM(high, low, timeperiod=14)
#MOM(close, timeperiod=10)
#PLUS_DI(high, low, close, timeperiod=14)
#PLUS_DM(high, low, timeperiod=14)
#PPO(close, fastperiod=12, slowperiod=26, matype=0)
#ROC(close, timeperiod=10)
#ROCP(close, timeperiod=10)
#ROCR(close, timeperiod=10)
#ROCR100(close, timeperiod=10)
#RSI(close, timeperiod=14)
#slowk, slowd = STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
#fastk, fastd = STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
#fastk, fastd = STOCHRSI(close, timeperiod=14, fastk_period=5, fastd_period=3, fastd_matype=0)
#TRIX(close, timeperiod=30)
#ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
#WILLR(high, low, close, timeperiod=14)

#================Volume Indicator Functions=================
#AD(high, low, close, volume)
#ADOSC(high, low, close, volume, fastperiod=3, slowperiod=10)
#OBV(close, volume)

#=================Volatility Indicator Functions======================
#ATR(high, low, close, timeperiod=14)
#NATR(high, low, close, timeperiod=14)
#TRANGE(high, low, close)

#=======================Price Transform Functions=====================
#AVGPRICE(open, high, low, close)
#MEDPRICE(high, low)
#TYPPRICE(high, low, close)
#WCLPRICE(high, low, close)

#=================Cycle Indicator Functions======================
#HT_DCPERIOD(close)
#HT_DCPHASE(close)
#inphase, quadrature = HT_PHASOR(close)
#sine, leadsine = HT_SINE(close)
#HT_TRENDMODE(close)

#=====================Pattern Recognition Functions==================
#CDL2CROWS(open, high, low, close)
#CDL3BLACKCROWS(open, high, low, close)
#CDL3INSIDE(open, high, low, close)
#CDL3LINESTRIKE(open, high, low, close)
#CDL3OUTSIDE(open, high, low, close)
#CDL3STARSINSOUTH(open, high, low, close)
#CDL3WHITESOLDIERS(open, high, low, close)
#CDLABANDONEDBABY(open, high, low, close, penetration=0)
#CDLADVANCEBLOCK(open, high, low, close)
#CDLBELTHOLD(open, high, low, close)
#CDLBREAKAWAY(open, high, low, close)
#CDLCLOSINGMARUBOZU(open, high, low, close)
#CDLCONCEALBABYSWALL(open, high, low, close)
#CDLCOUNTERATTACK(open, high, low, close)
#CDLDARKCLOUDCOVER(open, high, low, close, penetration=0)
#CDLDOJI(open, high, low, close)
#CDLDOJISTAR(open, high, low, close)
#CDLDRAGONFLYDOJI(open, high, low, close)
#CDLENGULFING(open, high, low, close)
#CDLEVENINGDOJISTAR(open, high, low, close, penetration=0)
#CDLEVENINGSTAR(open, high, low, close, penetration=0)
#CDLGAPSIDESIDEWHITE(open, high, low, close)
#CDLGRAVESTONEDOJI(open, high, low, close)
#CDLHAMMER(open, high, low, close)
#CDLHANGINGMAN(open, high, low, close)
#CDLHARAMI(open, high, low, close)
#CDLHARAMICROSS(open, high, low, close)
#CDLHIGHWAVE(open, high, low, close)
#CDLHIKKAKE(open, high, low, close)
#CDLHIKKAKEMOD(open, high, low, close)
#CDLHOMINGPIGEON(open, high, low, close)
#CDLIDENTICAL3CROWS(open, high, low, close)
#CDLINNECK(open, high, low, close)
#CDLINVERTEDHAMMER(open, high, low, close)
#CDLKICKING(open, high, low, close)
#CDLKICKINGBYLENGTH(open, high, low, close)
#CDLLADDERBOTTOM(open, high, low, close)
#CDLLONGLEGGEDDOJI(open, high, low, close)
#CDLLONGLINE(open, high, low, close)
#CDLMARUBOZU(open, high, low, close)
#CDLMATCHINGLOW(open, high, low, close)
#CDLMATHOLD(open, high, low, close, penetration=0)
#CDLMORNINGDOJISTAR(open, high, low, close, penetration=0)
#CDLMORNINGSTAR(open, high, low, close, penetration=0)
#CDLONNECK(open, high, low, close)
#CDLPIERCING(open, high, low, close)
#CDLRICKSHAWMAN(open, high, low, close)
#CDLRISEFALL3METHODS(open, high, low, close)
#CDLSEPARATINGLINES(open, high, low, close)
#CDLSHOOTINGSTAR(open, high, low, close)
#CDLSHORTLINE(open, high, low, close)
#CDLSPINNINGTOP(open, high, low, close)
#CDLSTALLEDPATTERN(open, high, low, close)
#CDLSTICKSANDWICH(open, high, low, close)
#CDLTAKURI(open, high, low, close)
#CDLTASUKIGAP(open, high, low, close)
#CDLTHRUSTING(open, high, low, close)
#CDLTRISTAR(open, high, low, close)
#CDLUNIQUE3RIVER(open, high, low, close)
#CDLUPSIDEGAP2CROWS(open, high, low, close)
#CDLXSIDEGAP3METHODS(open, high, low, close)

#=============================Statistic Functions======================
#BETA(high, low, timeperiod=5)
#CORREL(high, low, timeperiod=30)
#LINEARREG(close, timeperiod=14)
#LINEARREG_ANGLE(close, timeperiod=14)
#LINEARREG_INTERCEPT(close, timeperiod=14)
#LINEARREG_SLOPE(close, timeperiod=14)
#STDDEV(close, timeperiod=5, nbdev=1)
#TSF(close, timeperiod=14)
#VAR(close, timeperiod=5, nbdev=1)



